language: python
python:
  - "2.7"
  - "3.4"

env:
  - DJANGO_SPEC=Django~=1.5
  - DJANGO_SPEC=Django~=1.6
  - DJANGO_SPEC=Django~=1.7
  - DJANGO_SPEC=Django~=1.8

install:
  - pip install coveralls
  - pip install $DJANGO_SPEC
  - python setup.py install

script:
  - coverage run --source=rebar setup.py test

after_success:
  - coveralls
